railstutorial: "http://www.railstutorial.org/"
newsrailstutorial: "http://news.railstutorial.org/"
michaelhartl: "http://www.michaelhartl.com/"
bookrails: "http://www.railstutorial.org/book"
screencastsrails: "http://screencasts.railstutorial.org/"
rubyonrails: "http://rubyonrails.org/"
contactrails: "http://www.railstutorial.org/contact"
helprails: "http://www.railstutorial.org/help"
email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
gravatar_url: "https://secure.gravatar.com/avatar/%{gravatar_id}?s=%{gravatar_size}"
gra_email: "http://gravatar.com/emails"
length_name: 50
length_email: 255
gra_size: 80
pw_min: 6
user_gravatar_size: 50
per_page: 10
