railstutorial: "http://www.railstutorial.org/"
newsrailstutorial: "http://news.railstutorial.org/"
michaelhartl: "http://www.michaelhartl.com/"
bookrails: "http://www.railstutorial.org/book"
screencastsrails: "http://screencasts.railstutorial.org/"
rubyonrails: "http://rubyonrails.org/"
contactrails: "http://www.railstutorial.org/contact"
helprails: "http://www.railstutorial.org/help"
